/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:dc98d21b-9f73-4aef-86b8-220e9aded983",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_PJ7qdUYaX",
    "aws_user_pools_web_client_id": "4u3dv11kjduuoirt1f24kebecu",
    "oauth": {}
};


export default awsmobile;
