/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:8c5c760f-f8d5-46a4-bc8c-2341e623e55b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_anfHOd8Um",
    "aws_user_pools_web_client_id": "10l4bbplh976bnpa2bjmomv8nu",
    "oauth": {}
};


export default awsmobile;
